<?php
$array = array("Bilic Tereza",
"Cepo Cvitan Luka",
"Frankovic	Rea",
"Gale Antonela",
"Horvat	Tomislav",
"Ilijevic Josip",
"Kerim Alberto",
"Kosovic Bartol",
"Kupresak Marko",
"Matic Jan",
"Nogic Nino",
"Pavlekovic Dino",
"Rodic Tin",
"Rumiha	Petar",
"Savic Luka",
"Stracenski	Monika",
"Saric Matej",
"Skrlec	Luka",
"Splajt	Renato",
"Vlatkovic Josip",
"Vukovic Patrik",
"Zaninovic Ana");
